name: easy_design
description: EasyDesign Project
version: 1.0.0+3
issue_tracker: https://github.com/FightTech-VN/easy_design/issues
homepage: https://tech.fighttech.vn
documentation: https://github.com/FightTech-VN/easy_design.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
